version: '3.8'

services:

  project-production:
    container_name: production.project
    entrypoint: /entrypoint.sh
    build:
      context: ../../
      dockerfile: ./conf/production/Dockerfile
      args:
        - USER_ID=$UID
        - GROUP_ID=$GID
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_data:/vol/web
      - ../../project:/app
  

  # redis:
  #   image: redis:alpine
  #   container_name: production.redis
  #   ports:
  #     - "6379:6379"
    
  # celery:
  #   container_name: production.celery
  #   build:
  #     context: ../../
  #     dockerfile: ./conf/production/Dockerfile
  #     args:
  #       - USER_ID=$UID
  #       - GROUP_ID=$GID
  #   env_file:
  #     - .env
  #   command: celery -A project.production worker -l debug
  #   depends_on:
  #     - redis
  #   volumes:
  #     - static_data:/vol/web
  #     - ../../project:/app
  
volumes:
  static_data:

